[package]
name = "processing_a_series_of_items_with_iterators"
version = "0.1.0"
authors = ["Gabriel Segovia <gabriel.asa.1296@outlook.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
