[package]
name = "separating_modules_into_different_files"
version = "0.1.0"
authors = ["Gabriel Alejandro <gabriel.asa.1296@outlook.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
